import { jsPDF } from "jspdf";

export default async function generateProfilePDF(
  profile,
  recommendations = {}
) {
  const pdf = new jsPDF("p", "mm", "a4");

  let y = 20;
  const pageHeight = pdf.internal.pageSize.height;

  const checkPageBreak = (spaceNeeded = 10) => {
    if (y + spaceNeeded > pageHeight - 15) {
      pdf.addPage();
      y = 20;
    }
  };

  const addSection = (title, items = []) => {
    if (!items || items.length === 0) return;

    checkPageBreak(15);

    pdf.setFontSize(14);
    pdf.setFont("helvetica", "bold");
    pdf.text(title, 15, y);

    y += 8;

    pdf.setFontSize(11);
    pdf.setFont("helvetica", "normal");

    items.forEach((item) => {
      checkPageBreak(8);

      const text =
        typeof item === "string"
          ? item
          : item.skill_name ||
            item.name ||
            JSON.stringify(item);

      const lines = pdf.splitTextToSize(
        `• ${text}`,
        170
      );

      pdf.text(lines, 20, y);

      y += lines.length * 6;
    });

    y += 5;
  };

  // ==========================
  // Header
  // ==========================

  pdf.setFontSize(22);
  pdf.setFont("helvetica", "bold");
  pdf.text("DevInsight AI Report", 15, y);

  y += 12;

  pdf.setDrawColor(180);
  pdf.line(15, y, 195, y);

  y += 10;

  // ==========================
  // Profile Information
  // ==========================

  pdf.setFontSize(16);
  pdf.setFont("helvetica", "bold");
  pdf.text("Developer Information", 15, y);

  y += 10;

  pdf.setFontSize(11);
  pdf.setFont("helvetica", "normal");

  const profileInfo = [
    `GitHub Username: ${
      profile.github_username || "N/A"
    }`,
    `Developer Score: ${
      profile.developer_score ?? "N/A"
    }`,
    `Followers: ${
      profile.followers ?? "N/A"
    }`,
    `Stars: ${
      profile.total_stars ||
      profile.stars ||
      "N/A"
    }`,
    `Top Language: ${
      profile.top_language || "N/A"
    }`,
  ];

  profileInfo.forEach((line) => {
    checkPageBreak(8);

    pdf.text(line, 15, y);
    y += 7;
  });

  y += 5;

  // ==========================
  // Strengths
  // ==========================

  addSection(
    "Strengths",
    profile.strengths || []
  );

  // ==========================
  // Weaknesses
  // ==========================

  addSection(
    "Weaknesses",
    profile.weaknesses || []
  );

  // ==========================
  // Recommended Skills
  // ==========================

  addSection(
    "Recommended Skills",
    recommendations.recommended_skills ||
      []
  );

  // ==========================
  // Project Ideas
  // ==========================

  addSection(
    "Project Ideas",
    recommendations.project_ideas || []
  );

  // ==========================
  // Career Paths
  // ==========================

  addSection(
    "Career Paths",
    recommendations.career_paths || []
  );

  // ==========================
  // Footer
  // ==========================

  const totalPages = pdf.getNumberOfPages();

  for (let i = 1; i <= totalPages; i++) {
    pdf.setPage(i);

    pdf.setFontSize(10);

    pdf.text(
      `Generated by DevInsight AI`,
      15,
      290
    );

    pdf.text(
      `Page ${i} of ${totalPages}`,
      170,
      290
    );
  }

  pdf.save(
    `${profile.github_username || "developer"}-report.pdf`
  );
}